// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMjSTooaB2V_JqSvzwHlWcFc7g5moY5BU',
    appId: '1:1006614044559:web:605a4e7d5e5431146cb5fa',
    messagingSenderId: '1006614044559',
    projectId: 'trackerapp-98e8d',
    authDomain: 'trackerapp-98e8d.firebaseapp.com',
    storageBucket: 'trackerapp-98e8d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYknSmQC2ZLLNxoVzjT2CfqV36yX30x04',
    appId: '1:1006614044559:android:2b3eebfa1d011fca6cb5fa',
    messagingSenderId: '1006614044559',
    projectId: 'trackerapp-98e8d',
    storageBucket: 'trackerapp-98e8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjp3DSGpaB4Ee6H9RoruSqcgvUp9vjwyA',
    appId: '1:1006614044559:ios:3905865b42876c316cb5fa',
    messagingSenderId: '1006614044559',
    projectId: 'trackerapp-98e8d',
    storageBucket: 'trackerapp-98e8d.appspot.com',
    iosBundleId: 'com.example.trackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjp3DSGpaB4Ee6H9RoruSqcgvUp9vjwyA',
    appId: '1:1006614044559:ios:3905865b42876c316cb5fa',
    messagingSenderId: '1006614044559',
    projectId: 'trackerapp-98e8d',
    storageBucket: 'trackerapp-98e8d.appspot.com',
    iosBundleId: 'com.example.trackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMjSTooaB2V_JqSvzwHlWcFc7g5moY5BU',
    appId: '1:1006614044559:web:a64f2e89ed51655b6cb5fa',
    messagingSenderId: '1006614044559',
    projectId: 'trackerapp-98e8d',
    authDomain: 'trackerapp-98e8d.firebaseapp.com',
    storageBucket: 'trackerapp-98e8d.appspot.com',
  );
}
